name: Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: cmd

    steps:
      - uses: actions/checkout@v2

        # Setup dependencies
      - name: Setup dependencies
        run: |
          setlocal enableextensions enabledelayedexpansion
          mingw32-make setup
          endlocal

        # Compile the project with dependencies
      - name: Compile Project
        run: |
          setlocal enableextensions enabledelayedexpansion
          mingw32-make bin/app
          endlocal

        # Export the binary as artifact
      - name: Export binary
        uses: actions/upload-artifact@v2
        with:
          name: app.exe
          path: bin/app.exe

        # Clean binaries
      - name: Clean Project
        run: mingw32-make clean

        # Re-compile with other compiler
      - name: make bin/app CXX=g++
        run: mingw32-make bin/app CXX=g++
